version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.1.0

workflows:
  build-and-deploy:
    context: default
    filters:
      branches:
        only: "feature/mediaconvert"
    jobs:
      - add_ssh_keys
      - run:
          name: "Setup Environment Variables"
          command: |
            echo 'export TAG="${CIRCLE_TAG:1}"' >> $BASH_ENV
      - aws-ecr/build-and-push-image:
          repo: "447259465167.dkr.ecr.eu-west-1.amazonaws.com/aaquita/moto"
          tag: "latest"
          attach-workspace: true
          workspace-root: /home/circleci/project